- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zprofile: zprofile
    ~/.gitconfig: gitconfig

- create:
    - ~/downloads
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
