- defaults:
    link:
      relink: true

- clean: ['~']

- link:
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zprofile: zprofile
    ~/.gitconfig: gitconfig
    ~/.global_gitignore: global_gitignore
    ~/.tmux.conf: tmux.conf
    ~/.vim/ftplugin/css.vim: vim/ftplugin/css.vim
    ~/.vim/ftplugin/java.vim: vim/ftplugin/java.vim
    ~/.vim/ftplugin/python.vim: vim/ftplugin/python.vim
    ~/.vim/ftplugin/javascript.vim: vim/ftplugin/javascript.vim
    ~/.vim/ftplugin/c.vim: vim/ftplugin/c.vim
    ~/.vim/ftplugin/vim.vim: vim/ftplugin/vim.vim
    ~/.vim/ftplugin/html.vim: vim/ftplugin/html.vim
    ~/.vim/coc-settings.json: vim/coc-settings.json
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.config/nvim/coc-settings.json: nvim/coc-settings.json

- create:
    - ~/downloads
    - ~/.vim/undo-history

- shell:
  - [git submodule update --init --recursive, Installing submodules]
