format = """
$os\
$directory\
$hostname\
$git_branch\
$git_status\
$git_state\
$fill\
$cmd_duration $python$golang$java$env_var$time $jobs$azure$aws
[ ](bold green)"""

[character]
success_symbol = '[➜](bold green)'

[os]
format = "[$symbol]($style)"
# style = "bold blue"
disabled = false

[os.symbols]
Arch = " "
Linux = " "
Macos = " "

[username]
show_always = true
format = '[doctor doom]($style) '

[hostname]
ssh_only = true
format = "[$hostname]($style) "

[directory]
truncation_length = 1
truncation_symbol = ''

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
up_to_date = ''
conflicted = '[ mergeConflicts${count}](red)'
untracked = '[ ?${count}](yellow)'
stashed = '[ *${count}](yellow)'
modified = '[ !${count}](yellow)'
staged = ' +${count}'
renamed = '[ »${count}](yellow)'
deleted = '[ ✘${count}](yellow)'
ahead = ' ⇡${count}'
diverged = '[ ⇕⇡${ahead_count}⇣${behind_count}](red)'
behind = ' ⇣${count}'
style = 'bold green'

[python]
format = '[${symbol}($version )(\($virtualenv\) )]($style)'
style = 'bold cyan'
symbol = ' '

[golang]
format = '[$symbol($version )]($style)'
style = 'bold cyan'
symbol = ' '

[java]
format = '[${symbol}(${version} )]($style)'
symbol = ' '

[env_var.VAULT_ADDR]
format = "[ VAULT_ADDR=$env_value]($style) "
variable = 'VAULT_ADDR'
style = 'bold green'

[env_var.VAULT_NAMESPACE]
format = "[ VAULT_NAMESPACE=$env_value]($style) "
variable = 'VAULT_NAMESPACE'
style = 'bold green'

[fill]
symbol = ' '

[cmd_duration]
format = 'took [$duration]($style)'

[time]
disabled = false
format = '[ $time]($style)'

[jobs]
symbol = ""
style = "bold yellow"
number_threshold = 1
format = "[$symbol ]($style)"

[azure]
format = ' [$symbol($subscription)]($style) '
disabled = false
symbol = ' - '

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = ' - '
